### ISSUE TITLE
at dk.mrspring.kitchen.config.SandwichableConfig.findEntry(SandwichableConfig.java:85)

### ISSUE THREAD

**Issue by lightning02** [MrSpring/TheKitchenMod#11]
http://pastebin.com/0XyhDqDA
A crash occur to me just logging in the modpack i'm actually using.

**Comment by MrSpring** [comment]
That is not a caused by my mod. It happens because some other mod has not registered their items properly.
I'll release an update that should prevents this from happening. Please tell the modpack author to update to the latest version of my mod.
