### ISSUE TITLE
Frying Pan Not Using Up Item

### ISSUE THREAD

**Issue by GraySloth** [MrSpring/TheKitchenMod#12]
Placing a peanut, bacon, etc. in a frying pan adds the item to the frying pan but does not remove it from your inventory, duping it.

Mods used:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
MobiusCore-1.2.5_1.7.10.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
Waila-1.5.10_1.7.10.jar
TheKitchenMod-1.3.20-1.7.2-10.jar

**Comment by MrSpring** [comment]
Thanks for letting me know, and sorry for the late response.
