### ISSUE TITLE
3d

### ISSUE THREAD

**Issue by Yoshiiowo** [MrSpring/TheKitchenMod#8]
Whenever I try to make a sandwich i place the bread on the cutting board. Then, things like cheese slices,beef slices or whatever are not 3d they're just flat except for the bacon. Im using the latest version of the mod.
![2015-12-30_18 12 01](https://cloud.githubusercontent.com/assets/16489516/12053388/4d56b8c8-af21-11e5-9429-cd098c675d78.png)
![2015-12-30_18 11 29](https://cloud.githubusercontent.com/assets/16489516/12053395/59640814-af21-11e5-9da2-4e1b21d4e549.png)

**Comment by MrSpring** [comment]
To get 3D items you have to turn graphics to fancy. Or you can install OptiFine and and only turn 3D items on, to keep the extra performance.
Without OptiFine you go to "Options", "Video Settings..." and turn "Graphics" to fancy.
In OptiFine you go to "Options", "Video Settings...", "Details..." and turn "Dropped Items" to fancy.﻿
